import { connectToDatabase } from '@/lib/db/connect';
import { QuizModel } from '@/models/Quiz';
import { QuestionModel } from '@/models/Question';
import mongoose from 'mongoose';

export async function seedQuizMaterials(trainerIdString: string = '650000000000000000000001') {
  await connectToDatabase();
  const trainerId = new mongoose.Types.ObjectId(trainerIdString);

  // Clear previous seeded materials to ensure exact fresh synchronization
  const seededTitles = [
    'Activity 1: AI or Not? Challenge',
    'Activity 2: AI Technology Detective',
    'Activity 3: AI Solution & Workflow Challenge',
    'Activity 4: Prompt Engineering Challenge',
  ];

  await QuizModel.deleteMany({ title: { $in: seededTitles } });

  // -------------------------------------------------------------
  // QUIZ 1: "Activity 1: AI or Not?" (15 Binary Choice Questions)
  // -------------------------------------------------------------
  const activity1QuestionsData = [
    {
      questionText: "A music app studies a listener's previous songs, skips and playlists, then recommends songs the listener may enjoy.",
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: "The system uses patterns in the listener's behavior to make personalized recommendations. This is an AI use case.",
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: "A refrigerator automatically starts its cooling system when its internal temperature rises above 5°C.",
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 1,
      explanation: 'The refrigerator follows a fixed rule: if the temperature crosses a set threshold, turn cooling on. That is automation, not AI.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: "A banking system examines a customer's transaction patterns and identifies unusual activity that may indicate fraud.",
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The system analyzes data patterns to identify unusual behavior and potential fraud. This is an AI use case.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: 'A phone automatically switches to silent mode every day between 10 PM and 7 AM because the user has configured a schedule.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 1,
      explanation: 'The phone is following a predefined schedule. It does not need to learn or interpret anything, so this is not AI.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: 'An online shopping website looks at what a customer has viewed and purchased and recommends products they might be interested in.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The system uses customer behavior patterns to make personalized recommendations. This is an AI use case.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: 'A car automatically turns on its headlights when a light sensor detects that the surroundings have become dark.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 1,
      explanation: 'A sensor detects a simple condition and triggers a predefined action. This is ordinary automation, not AI.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: 'A handwriting application analyzes a person\'s handwritten notes and converts them into editable digital text.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The system has to recognize complex visual patterns and interpret them as characters and words. That is an AI capability.',
      category: 'Computer Vision',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'A phone unlocks when its front camera recognizes the user\'s face.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The phone analyzes facial features and compares the detected pattern with the enrolled face. This is an AI use case.',
      category: 'Computer Vision',
      difficulty: 'EASY',
    },
    {
      questionText: 'A travel application predicts that a flight is likely to be delayed by analyzing historical flight patterns, weather information and current flight data.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The system uses data and patterns to predict a future event. That is an AI use case.',
      category: 'Machine Learning',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'A traffic light changes from green to yellow to red according to a programmed timing sequence.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 1,
      explanation: 'A sensor detects a simple condition and the machine follows a predefined safety rule. This is not AI.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: 'A vending machine gives you the selected drink or snack after you insert the required payment.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 1,
      explanation: 'The machine is executing programmed control rules. It is automatic, but it does not require AI.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: 'A photo app automatically groups pictures based on what is visible in them, such as pets, beaches or food.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The app analyzes image content and recognizes visual patterns to categorize photos. That is an AI use case.',
      category: 'Computer Vision',
      difficulty: 'EASY',
    },
    {
      questionText: 'Amazon Alexa understands when you say, "Set an alarm for 6 AM tomorrow."',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The system must interpret human speech and understand the user\'s request. Speech and language understanding are AI capabilities.',
      category: 'NLP',
      difficulty: 'EASY',
    },
    {
      questionText: 'An office printer automatically prints a report every Monday at 9 AM because a schedule was configured.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 1,
      explanation: 'The printer is simply following a schedule that was configured in advance. This is not AI.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: 'A weather app predicts whether it will rain tomorrow by analyzing weather data and patterns.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The system analyzes data and patterns to make a prediction about a future event. This is an AI use case.',
      category: 'Machine Learning',
      difficulty: 'EASY',
    },
  ];

  const q1Docs = await QuestionModel.insertMany(
    activity1QuestionsData.map((q) => ({
      ...q,
      trainerId,
      timeLimit: 15,
      points: 1000,
      tags: ['AI-vs-NotAI', 'Workshop-Activity1'],
    }))
  );

  const quiz1 = await QuizModel.create({
    trainerId,
    title: 'Activity 1: AI or Not? Challenge',
    category: 'AI Foundations',
    description: 'Mini Activity — 15 Situations to classify whether a system uses AI or ordinary automation.',
    instructions: 'Examine each situation and select AI or Not AI based on whether it learns from data or uses fixed rules.',
    questionIds: q1Docs.map((doc) => doc._id),
    status: 'READY',
    defaultTimeLimit: 15,
    defaultPoints: 1000,
  });

  // -------------------------------------------------------------
  // QUIZ 2: "Activity 2: AI Technology Detective" (Exactly 2 Drag & Drop Activities)
  // -------------------------------------------------------------
  const activity2QuestionsData = [
    {
      questionText: 'Activity 1 — Sort the Solutions',
      questionType: 'DRAG_AND_DROP',
      options: [
        'Customer churn prediction',
        'House price prediction',
        'Next month\'s sales forecast',
        'Handwritten digit recognition',
        'Speech recognition',
        'Complex medical image learning',
        'Customer email classification',
        'Meeting summary',
        'Language translation',
        'Factory defect detection',
        'Traffic camera vehicle counting',
        'Reading a barcode from a camera',
      ],
      categories: [
        { id: 'ml', title: 'Traditional Machine Learning', description: 'Structured business data used to predict or classify.' },
        { id: 'dl', title: 'Deep Learning', description: 'Neural networks learn complex patterns from many examples.' },
        { id: 'nlp', title: 'Natural Language Processing (NLP)', description: 'The main job is to understand or work with human language.' },
        { id: 'cv', title: 'Computer Vision', description: 'The main job is to understand images or video.' },
      ],
      categoryAssignments: {
        '0': 'ml',
        '1': 'ml',
        '2': 'ml',
        '3': 'dl',
        '4': 'dl',
        '5': 'dl',
        '6': 'nlp',
        '7': 'nlp',
        '8': 'nlp',
        '9': 'cv',
        '10': 'cv',
        '11': 'cv',
      },
      explanation: 'Drag each of the 12 cards into the category that best describes it. You can also click a card, then click a category.',
      category: 'AI Architectures',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Activity 2 — Choose the AI Combination',
      questionType: 'DRAG_AND_DROP',
      options: [
        'Case 1: A customer-service voice assistant must understand what customers say and use a neural network trained on thousands of voice examples. What combination is needed?',
        'Case 2: A factory wants to use camera images to identify damaged products. What combination is most appropriate?',
        'Case 3: A company wants to predict which employees may leave using salary, tenure, age, department and previous performance data. What is the clearest approach?',
        'Case 4: A company wants to automatically classify customer emails as complaint, question, compliment or refund request. What combination best describes the solution?',
        'Case 5: A security system uses camera footage and a neural network to detect whether violence or fighting is happening in the scene. What combination is needed?',
        'Case 6: A bakery wants to predict how many items it will sell next week using previous sales, prices, promotions, day of the week, seasonality and other sales information. What is the clearest approach?',
      ],
      categories: [
        { id: 'nlp_dl', title: 'NLP + Deep Learning' },
        { id: 'cv_dl', title: 'Computer Vision + Deep Learning' },
        { id: 'cv_tml', title: 'Computer Vision + Traditional Machine Learning' },
        { id: 'nlp_cv', title: 'NLP + Computer Vision' },
        { id: 'nlp_tml', title: 'NLP + Traditional Machine Learning' },
        { id: 'tml', title: 'Traditional Machine Learning only' },
        { id: 'nlp_ml', title: 'NLP + Machine Learning' },
      ],
      categoryAssignments: {
        '0': 'nlp_dl',
        '1': 'cv_dl',
        '2': 'tml',
        '3': 'nlp_ml',
        '4': 'cv_dl',
        '5': 'tml',
      },
      explanation: 'Now choose the best combination for each real-life case. Some cases use one concept; others combine a problem area with a learning approach.',
      category: 'AI Architectures',
      difficulty: 'MEDIUM',
    },
  ];

  const q2Docs = await QuestionModel.insertMany(
    activity2QuestionsData.map((q) => ({
      ...q,
      trainerId,
      timeLimit: 30,
      points: 1000,
      tags: ['AI-Detective', 'Workshop-Activity2'],
    }))
  );

  const quiz2 = await QuizModel.create({
    trainerId,
    title: 'Activity 2: AI Technology Detective',
    category: 'AI Classification',
    description: 'Learn the difference between Traditional ML, Deep Learning, NLP, and Computer Vision.',
    instructions: 'Categorize solutions into technology areas and select the best AI technology combinations.',
    questionIds: q2Docs.map((doc) => doc._id),
    status: 'READY',
    defaultTimeLimit: 30,
    defaultPoints: 1000,
  });

  // -------------------------------------------------------------
  // QUIZ 3: "Activity 3: AI Solution Challenge" (5 Interactive Solution Scenarios)
  // -------------------------------------------------------------
  const activity3QuestionsData = [
    {
      questionText: 'Marketing Content',
      questionType: 'SOLUTION_CHALLENGE',
      options: ['A product team needs 20 social media captions and 5 product descriptions for a new launch. A human will review everything before publishing.'],
      explanation: 'The main job is creating content. Generative AI is the simplest fit, while a human controls the final publication.',
      category: 'Marketing',
      topic: 'Marketing Content',
      difficulty: 'EASY',
      solutionChallengeData: {
        icon: '✍️',
        dept: 'Marketing',
        answer: 'Generative AI',
        capabilities: [
          { text: 'Generate content', isCorrect: true },
          { text: 'Use product information', isCorrect: true },
          { text: 'Control tone and style', isCorrect: true },
          { text: 'Create multiple variations', isCorrect: true },
          { text: 'Human approval', isCorrect: true },
          { text: 'Access CRM records', isCorrect: false },
          { text: 'Publish content without human review', isCorrect: false },
          { text: 'Change product pricing', isCorrect: false },
          { text: 'Monitor customer replies', isCorrect: false },
        ],
        workflow: [
          { text: 'Enter product information', isCorrect: true },
          { text: 'Generate captions', isCorrect: true },
          { text: 'Generate product descriptions', isCorrect: true },
          { text: 'Create alternative versions', isCorrect: true },
          { text: 'Human reviews and edits', isCorrect: true },
          { text: 'Approve for publishing', isCorrect: true },
          { text: 'Update CRM records', isCorrect: false },
          { text: 'Send invoices', isCorrect: false },
          { text: 'Publish content without human review', isCorrect: false },
        ],
        autonomy: [
          { title: 'Human makes the decisions', isCorrect: true, description: 'A person reviews and approves the final content.' },
          { title: 'AI handles routine tasks, human handles exceptions', isCorrect: false, description: 'More autonomy than this scenario requires.' },
          { title: 'AI makes decisions and acts on its own', isCorrect: false, description: 'This conflicts with the human-review requirement.' },
        ],
        controlTitle: 'Step 4: Decide how the AI and human work together',
        why: 'The main job is creating content. Generative AI is the simplest fit, while a human controls the final publication.',
      },
    },
    {
      questionText: 'Sales Manager Assistant',
      questionType: 'SOLUTION_CHALLENGE',
      options: ['Every Monday, a sales manager wants AI to summarize the weekly sales spreadsheet, highlight unusual changes, and suggest questions the manager should investigate.'],
      explanation: 'The AI works alongside the sales manager. It analyzes information and provides suggestions, while the manager remains responsible for the decision.',
      category: 'Sales',
      topic: 'Sales Manager Assistant',
      difficulty: 'EASY',
      solutionChallengeData: {
        icon: '📊',
        dept: 'Sales',
        answer: 'AI Copilot',
        capabilities: [
          { text: 'Analyze sales data', isCorrect: true },
          { text: 'Summarize findings', isCorrect: true },
          { text: 'Highlight unusual changes', isCorrect: true },
          { text: 'Suggest investigation questions', isCorrect: true },
          { text: 'Human review and decision', isCorrect: true },
          { text: 'Send customer emails automatically', isCorrect: false },
          { text: 'Update CRM automatically', isCorrect: false },
          { text: 'Place sales orders', isCorrect: false },
          { text: 'Monitor warehouse inventory', isCorrect: false },
        ],
        workflow: [
          { text: 'Upload sales spreadsheet', isCorrect: true },
          { text: 'Analyze weekly performance', isCorrect: true },
          { text: 'Identify unusual changes', isCorrect: true },
          { text: 'Generate manager summary', isCorrect: true },
          { text: 'Suggest investigation questions', isCorrect: true },
          { text: 'Manager reviews and decides', isCorrect: true },
          { text: 'Send emails to customers', isCorrect: false },
          { text: 'Update CRM automatically', isCorrect: false },
          { text: 'Place a sales order', isCorrect: false },
        ],
        autonomy: [
          { title: 'Human makes the decisions', isCorrect: true, description: 'The manager reviews the analysis and decides what to do.' },
          { title: 'AI handles routine tasks, human handles exceptions', isCorrect: false, description: 'More autonomy than this decision-support scenario requires.' },
          { title: 'AI makes decisions and acts on its own', isCorrect: false, description: 'The manager remains responsible for decisions.' },
        ],
        controlTitle: 'Step 4: Decide how the AI and human work together',
        why: 'The AI works alongside the sales manager. It analyzes information and provides suggestions, while the manager remains responsible for the decision.',
      },
    },
    {
      questionText: 'Customer Support Task',
      questionType: 'SOLUTION_CHALLENGE',
      options: ['A support system receives a customer request. AI should read it, check the customer\'s account, find the answer in the knowledge base, update the ticket, and escalate complex cases.'],
      explanation: 'The AI must complete several connected steps and use business tools to act. That makes an AI Agent the best fit.',
      category: 'Customer Service',
      topic: 'Customer Support Task',
      difficulty: 'MEDIUM',
      solutionChallengeData: {
        icon: '🤖',
        dept: 'Customer Service',
        answer: 'AI Agent',
        capabilities: [
          { text: 'Understand the customer request', isCorrect: true },
          { text: 'Access CRM/account data', isCorrect: true },
          { text: 'Search the knowledge base', isCorrect: true },
          { text: 'Generate a response', isCorrect: true },
          { text: 'Update the support ticket', isCorrect: true },
          { text: 'Escalate complex cases', isCorrect: true },
          { text: 'Create marketing content', isCorrect: false },
          { text: 'Change product pricing', isCorrect: false },
          { text: 'Approve refunds automatically', isCorrect: false },
        ],
        workflow: [
          { text: 'Receive customer request', isCorrect: true },
          { text: 'Understand the issue', isCorrect: true },
          { text: 'Check customer account', isCorrect: true },
          { text: 'Search knowledge base', isCorrect: true },
          { text: 'Prepare customer response', isCorrect: true },
          { text: 'Update support ticket', isCorrect: true },
          { text: 'Escalate complex case', isCorrect: true },
          { text: 'Create social media post', isCorrect: false },
          { text: 'Change product price', isCorrect: false },
          { text: 'Close every ticket without review', isCorrect: false },
        ],
        autonomy: [
          { title: 'AI handles routine tasks, human handles exceptions', isCorrect: true, description: 'The agent handles normal cases and escalates difficult cases.' },
          { title: 'Human makes the decisions', isCorrect: false, description: 'Too much human involvement for the routine workflow.' },
          { title: 'AI makes decisions and acts on its own', isCorrect: false, description: 'Too much autonomy because complex cases require escalation.' },
        ],
        controlTitle: 'Step 4: Decide how the AI and human work together',
        why: 'The AI must complete several connected steps and use business tools to act. That makes an AI Agent the best fit.',
      },
    },
    {
      questionText: 'Customer Churn Prediction',
      questionType: 'SOLUTION_CHALLENGE',
      options: ['A company has 3 years of customer data and wants to predict which customers are most likely to cancel their subscription next month so the sales team can contact them early.'],
      explanation: 'Machine Learning learns patterns from historical data and uses them to predict which customers may cancel. The prediction supports a business decision; it does not make the decision itself.',
      category: 'Customer Analytics',
      topic: 'Customer Churn Prediction',
      difficulty: 'EASY',
      solutionChallengeData: {
        icon: '📈',
        dept: 'Customer Analytics',
        answer: 'Machine Learning',
        capabilities: [
          { text: 'Historical customer data', isCorrect: true },
          { text: 'Relevant customer features', isCorrect: true },
          { text: 'Train a prediction model', isCorrect: true },
          { text: 'Test model accuracy', isCorrect: true },
          { text: 'New customer data for prediction', isCorrect: true },
          { text: 'Generate social media posts', isCorrect: false },
          { text: 'Write marketing emails', isCorrect: false },
          { text: 'Create an approval workflow', isCorrect: false },
          { text: 'Search company documents', isCorrect: false },
        ],
        workflow: [
          { text: 'Collect historical customer data', isCorrect: true },
          { text: 'Prepare and clean data', isCorrect: true },
          { text: 'Train ML model', isCorrect: true },
          { text: 'Test model accuracy', isCorrect: true },
          { text: 'Use new data to predict churn', isCorrect: true },
          { text: 'Review prediction results', isCorrect: true },
          { text: 'Generate marketing content', isCorrect: false },
          { text: 'Send invoices', isCorrect: false },
          { text: 'Create a chatbot response', isCorrect: false },
        ],
        autonomy: [
          { title: 'Human reviews predictions before taking action', isCorrect: true, description: 'The model predicts; a person decides how to act.' },
          { title: 'AI automatically contacts every predicted customer', isCorrect: false, description: 'The prediction should support the sales team\'s decision.' },
          { title: 'AI automatically cancels predicted customers', isCorrect: false, description: 'A prediction should not directly trigger cancellation.' },
        ],
        controlTitle: 'Step 4: Decide how the prediction should be used',
        why: 'Machine Learning learns patterns from historical data and uses them to predict which customers may cancel. The prediction supports a business decision; it does not make the decision itself.',
      },
    },
    {
      questionText: 'Employee Leave Request',
      questionType: 'SOLUTION_CHALLENGE',
      options: ['Whenever an employee submits a leave request, the system should check whether the required information is complete and send the request to the employee\'s manager for approval.'],
      explanation: 'The process follows predefined rules. No learning, prediction or content generation is required, so Automation is the simplest solution.',
      category: 'HR',
      topic: 'Employee Leave Request',
      difficulty: 'EASY',
      solutionChallengeData: {
        icon: '🔄',
        dept: 'HR',
        answer: 'Automation',
        capabilities: [
          { text: 'Trigger when a leave request is submitted', isCorrect: true },
          { text: 'Check required fields', isCorrect: true },
          { text: 'Send request to manager', isCorrect: true },
          { text: 'Wait for approval', isCorrect: true },
          { text: 'Notify employee', isCorrect: true },
          { text: 'Predict employee behaviour', isCorrect: false },
          { text: 'Train an ML model', isCorrect: false },
          { text: 'Generate marketing content', isCorrect: false },
          { text: 'Search company documents', isCorrect: false },
        ],
        workflow: [
          { text: 'Employee submits leave request', isCorrect: true },
          { text: 'Check required information', isCorrect: true },
          { text: 'Send to manager', isCorrect: true },
          { text: 'Manager approves or rejects', isCorrect: true },
          { text: 'Notify employee', isCorrect: true },
          { text: 'Predict employee behaviour', isCorrect: false },
          { text: 'Generate an AI response', isCorrect: false },
          { text: 'Automatically approve every request', isCorrect: false },
        ],
        autonomy: [
          { title: 'If information is missing, ask the employee to complete it', isCorrect: true, description: 'This follows the defined rule.' },
          { title: 'If information is missing, AI guesses the missing information', isCorrect: false, description: 'A rule-based process should not invent missing information.' },
          { title: 'If information is missing, automatically approve the request', isCorrect: false, description: 'Missing information should not result in automatic approval.' },
        ],
        controlTitle: 'Step 4: Decide what happens when information is missing',
        why: 'The process follows predefined rules. No learning, prediction or content generation is required, so Automation is the simplest solution.',
      },
    },

    // Part 2: Workflow Automation Challenges (Sequence)
    {
      questionText: 'Build the Automated Leave Request Workflow in the exact logical sequence:',
      questionType: 'CORRECT_SEQUENCE',
      options: [
        'Form Submitted',
        'Check Leave Details',
        'Manager Approval',
        'Send Approval / Rejection Notification',
      ],
      correctOrder: [0, 1, 2, 3],
      explanation: 'Leave workflow sequence: Form Submitted -> Check Details -> Manager Approval -> Send Notification.',
      category: 'Workflow Automation',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Build the Automated Sales Report Workflow in the exact logical sequence:',
      questionType: 'CORRECT_SEQUENCE',
      options: [
        'Monthly Schedule',
        'Get Sales Data',
        'Prepare Sales Report',
        'Send Report to Management',
      ],
      correctOrder: [0, 1, 2, 3],
      explanation: 'Sales report workflow sequence: Schedule -> Fetch Data -> Prepare Report -> Deliver to Management.',
      category: 'Workflow Automation',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Build the Customer Complaint Automation Workflow in the exact logical sequence:',
      questionType: 'CORRECT_SEQUENCE',
      options: [
        'Complaint Received',
        'Capture Complaint Details',
        'Check Complaint Priority',
        'High Priority → Escalate to Manager',
        'Normal Priority → Send Acknowledgement',
        'Update Complaint Status',
      ],
      correctOrder: [0, 1, 2, 3, 4, 5],
      explanation: 'Complaint workflow: Received -> Capture Details -> Priority Check -> Escalation/Acknowledgement Branches -> Update Status.',
      category: 'Workflow Automation',
      difficulty: 'HARD',
    },

    // Part 3: AI Governance Questions
    {
      questionText: 'A team wants to summarize customer support conversations containing names, emails, and phone numbers. What should the team do before using an AI tool?',
      questionType: 'MCQ',
      options: [
        'Use a public AI tool directly because it is faster',
        'Remove or anonymize sensitive personal information before using AI',
        'Upload everything because the AI tool is only used internally',
        'Ask employees to manually copy sensitive details into public AI prompt boxes',
      ],
      correctOptionIndex: 1,
      explanation: 'Sensitive personal identifiable information (PII) must be anonymized before submitting data to AI services.',
      category: 'AI Governance',
      difficulty: 'EASY',
    },
    {
      questionText: 'An employee uses AI to prepare a financial report. The AI generates an incorrect figure, and the employee submits it to management without checking. Who is responsible for ensuring accuracy?',
      questionType: 'MCQ',
      options: [
        'The AI is responsible because it generated the number',
        'The AI vendor company is responsible for the financial report',
        'The employee/team using the AI must review and verify the output',
        'Nobody is responsible because AI can hallucinate',
      ],
      correctOptionIndex: 2,
      explanation: 'Accountability remains with the human professional using the AI tool.',
      category: 'AI Governance',
      difficulty: 'EASY',
    },
    {
      questionText: 'Which AI use case requires the strongest governance and risk controls?',
      questionType: 'MCQ',
      options: [
        'AI creates ideas for a company\'s social media posts',
        'AI summarizes an internal team meeting',
        'AI recommends whether a job applicant should be hired',
        'AI creates a draft internal newsletter',
      ],
      correctOptionIndex: 2,
      explanation: 'Employment, hiring, and financial credit decisions carry high ethical/legal impact and require stringent governance controls.',
      category: 'AI Governance',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Select all responsible actions to take when an AI chatbot gives inconsistent customer answers:',
      questionType: 'MCQ',
      options: [
        'Monitor chatbot outputs & test with representative questions',
        'Allow the chatbot to run completely unmonitored',
        'Define clear escalation triggers to hand over complex cases to human agents',
        'Investigate and correct recurring errors in the knowledge base',
      ],
      correctOptionIndex: 0,
      explanation: 'Responsible AI deployments require output monitoring, safety testing, human handover rules, and root cause fixes.',
      category: 'AI Governance',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Order the governance steps for introducing an AI system for employee performance data:',
      questionType: 'CORRECT_SEQUENCE',
      options: [
        'Define purpose and intended use',
        'Identify data being used',
        'Assess privacy, security, bias and risks',
        'Establish human oversight and approval',
        'Test the AI system',
        'Monitor system after deployment',
      ],
      correctOrder: [0, 1, 2, 3, 4, 5],
      explanation: 'Governance lifecycle: Purpose -> Data -> Risk Assessment -> Governance & Oversight -> Testing -> Ongoing Monitoring.',
      category: 'AI Governance',
      difficulty: 'HARD',
    },
  ];

  const q3Docs = await QuestionModel.insertMany(
    activity3QuestionsData.map((q) => ({
      ...q,
      trainerId,
      timeLimit: 30,
      points: 1000,
      tags: ['AI-Solution-Challenge', 'Workshop-Activity3'],
    }))
  );

  const quiz3 = await QuizModel.create({
    trainerId,
    title: 'Activity 3: AI Solution & Workflow Challenge',
    category: 'AI Solution Architecture',
    description: 'Solve real-world business scenarios, build end-to-end automated workflows, and master AI governance.',
    instructions: 'Select optimal AI approaches, build ordered workflows, and choose responsible AI governance answers.',
    questionIds: q3Docs.map((doc) => doc._id),
    status: 'READY',
    defaultTimeLimit: 30,
    defaultPoints: 1000,
  });

  // -------------------------------------------------------------
  // QUIZ 4: "Activity 4: Prompt Engineering Challenge (RCTOF)" (4 Prompt Builder Exercises)
  // -------------------------------------------------------------
  const activity4QuestionsData = [
    {
      questionText: 'Exercise 1 — Build an Effective Prompt',
      questionType: 'PROMPT_BUILDER',
      options: [
        'Act as a professional meeting summarization assistant.',
        'The audience is busy managers who need a quick overview.',
        'Summarize the meeting and identify key decisions, action items, and responsible people.',
        'Present the answer with clear headings and bullet points.',
        'Use only information from the supplied transcript and do not invent details.',
        'Act as a meeting participant.',
        'Focus mainly on rewriting the transcript into more formal language.',
        'Present the summary as one continuous paragraph without headings or bullet points.',
        'Include only the main topic discussed in the meeting.',
        'Write the summary without mentioning any action items.',
      ],
      promptBuilderData: {
        scenarioTitle: 'Exercise 1 — Build an Effective Prompt',
        scenarioText: 'A management team wants to use AI to turn a long business meeting transcript into a clear summary. The managers are busy and need the important decisions, action items, and responsibilities quickly. Build a prompt for an AI assistant that clearly defines who the AI should act as, who the response is for, what the AI should achieve, how the answer should be presented, and one clear limitation.',
        instruction: 'Select the useful pieces, arrange them, and review the prompt you created.',
        pieces: [
          { text: 'Use only information from the supplied transcript and do not invent details.', isCorrect: true },
          { text: 'Act as a professional meeting summarization assistant.', isCorrect: true },
          { text: 'Write the summary without mentioning any action items.', isCorrect: false },
          { text: 'Summarize the meeting and identify key decisions, action items, and responsible people.', isCorrect: true },
          { text: 'Focus mainly on rewriting the transcript into more formal language.', isCorrect: false },
          { text: 'The audience is busy managers who need a quick overview.', isCorrect: true },
          { text: 'Act as a meeting participant.', isCorrect: false },
          { text: 'Present the answer with clear headings and bullet points.', isCorrect: true },
          { text: 'Present the summary as one continuous paragraph without headings or bullet points.', isCorrect: false },
          { text: 'Include only the main topic discussed in the meeting.', isCorrect: false },
        ],
      },
      explanation: 'RCTOF Framework: Role (Professional meeting summarization assistant) + Context (Busy managers needing quick overview) + Task (Summarize decisions, action items & responsibilities) + Format (Clear headings & bullet points) + Constraint (Use only supplied transcript).',
      category: 'Prompt Engineering',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Exercise 2 — Improve a Weak Prompt',
      questionType: 'PROMPT_BUILDER',
      options: [
        'Act as a sales performance analyst.',
        'The audience is a sales manager preparing for a management meeting.',
        'Analyze the monthly sales data, identify the best and worst regions, and give three actionable recommendations.',
        'Present the result with a short management summary followed by bullet points.',
        'Use only the supplied sales data and do not invent figures.',
        'Act as a software developer.',
        'The audience is a group of database administrators.',
        'Write Python code to analyze the data.',
        'Create a social media campaign.',
        'Use technical language and include every available detail.',
      ],
      promptBuilderData: {
        scenarioTitle: 'Exercise 2 — Improve a Weak Prompt',
        scenarioText: 'Weak prompt: “Analyze this sales data and make a report.”\n\nBusiness requirement: The sales manager wants monthly sales performance, the best and worst regions, and three actionable recommendations for a management meeting. Improve the prompt by defining the role, context, goal, format and constraint.',
        instruction: 'Select the useful pieces, arrange them, and review the prompt you created.',
        pieces: [
          { text: 'Act as a sales performance analyst.', isCorrect: true },
          { text: 'The audience is a sales manager preparing for a management meeting.', isCorrect: true },
          { text: 'Analyze the monthly sales data, identify the best and worst regions, and give three actionable recommendations.', isCorrect: true },
          { text: 'Present the result with a short management summary followed by bullet points.', isCorrect: true },
          { text: 'Use only the supplied sales data and do not invent figures.', isCorrect: true },
          { text: 'Act as a software developer.', isCorrect: false },
          { text: 'The audience is a group of database administrators.', isCorrect: false },
          { text: 'Write Python code to analyze the data.', isCorrect: false },
          { text: 'Create a social media campaign.', isCorrect: false },
          { text: 'Use technical language and include every available detail.', isCorrect: false },
        ],
      },
      explanation: 'RCTOF Framework: Role (Sales performance analyst) + Context (Sales manager preparing for meeting) + Task (Analyze monthly sales, best/worst regions, 3 recommendations) + Format (Short management summary + bullets) + Constraint (Use supplied data only).',
      category: 'Prompt Engineering',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Exercise 3 — Build a Prompt for a New Situation',
      questionType: 'PROMPT_BUILDER',
      options: [
        'Act as a customer service manager.',
        'The audience is a customer service team.',
        'Create a short response explaining how to handle an angry customer professionally.',
        'Use a numbered list with five practical steps.',
        'Keep the response under 150 words and do not blame the customer.',
        'Act as a graphic designer.',
        'The audience is software engineers.',
        'Write JavaScript code for a customer portal.',
        'Use a long essay format.',
        'Include unrelated product specifications.',
      ],
      promptBuilderData: {
        scenarioTitle: 'Exercise 3 — Build a Prompt for a New Situation',
        scenarioText: 'A customer service team needs an AI assistant to help employees handle angry customers professionally. Build an effective prompt using one clear role, context, goal, format and constraint.',
        instruction: 'Select the useful pieces, arrange them, and review the prompt you created.',
        pieces: [
          { text: 'Act as a customer service manager.', isCorrect: true },
          { text: 'The audience is a customer service team.', isCorrect: true },
          { text: 'Create a short response explaining how to handle an angry customer professionally.', isCorrect: true },
          { text: 'Use a numbered list with five practical steps.', isCorrect: true },
          { text: 'Keep the response under 150 words and do not blame the customer.', isCorrect: true },
          { text: 'Act as a graphic designer.', isCorrect: false },
          { text: 'The audience is software engineers.', isCorrect: false },
          { text: 'Write JavaScript code for a customer portal.', isCorrect: false },
          { text: 'Use a long essay format.', isCorrect: false },
          { text: 'Include unrelated product specifications.', isCorrect: false },
        ],
      },
      explanation: 'RCTOF Framework: Role (Customer service manager) + Context (Customer service team) + Task (Handle angry customers professionally) + Format (Numbered list with 5 steps) + Constraint (Under 150 words & no customer blame).',
      category: 'Prompt Engineering',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Exercise 4 — Build a Prompt from a Business Requirement',
      questionType: 'PROMPT_BUILDER',
      options: [
        'Act as an HR communication specialist.',
        'The audience is employees who will receive a company policy update.',
        'Create a clear prompt for AI to explain the policy change and what employees need to do.',
        'Present the answer with a short summary followed by employee action points.',
        'Use only the information provided in the policy and do not invent rules.',
        'Act as a financial trader.',
        'Write a detailed Python application.',
        'Generate a social media advertisement.',
        'Assume information that is not in the policy.',
        'Use technical legal language throughout.',
      ],
      promptBuilderData: {
        scenarioTitle: 'Exercise 4 — Build a Prompt from a Business Requirement',
        scenarioText: 'A company is communicating a policy update to employees. Create an effective prompt that instructs AI to explain the change and clearly tell employees what they need to do. Use one role, context, goal, format and constraint.',
        instruction: 'Select the useful pieces, arrange them, and review the prompt you created.',
        pieces: [
          { text: 'Act as an HR communication specialist.', isCorrect: true },
          { text: 'The audience is employees who will receive a company policy update.', isCorrect: true },
          { text: 'Create a clear prompt for AI to explain the policy change and what employees need to do.', isCorrect: true },
          { text: 'Present the answer with a short summary followed by employee action points.', isCorrect: true },
          { text: 'Use only the information provided in the policy and do not invent rules.', isCorrect: true },
          { text: 'Act as a financial trader.', isCorrect: false },
          { text: 'Write a detailed Python application.', isCorrect: false },
          { text: 'Generate a social media advertisement.', isCorrect: false },
          { text: 'Assume information that is not in the policy.', isCorrect: false },
          { text: 'Use technical legal language throughout.', isCorrect: false },
        ],
      },
      explanation: 'RCTOF Framework: Role (HR communication specialist) + Context (Employees receiving policy update) + Task (Explain policy change & action items) + Format (Short summary + employee action points) + Constraint (Use provided policy info only).',
      category: 'Prompt Engineering',
      difficulty: 'MEDIUM',
    },
  ];

  const q4Docs = await QuestionModel.insertMany(
    activity4QuestionsData.map((q) => ({
      ...q,
      trainerId,
      timeLimit: 30,
      points: 1000,
      tags: ['RCTOF-Prompting', 'Workshop-Activity4'],
    }))
  );

  const quiz4 = await QuizModel.create({
    trainerId,
    title: 'Activity 4: Prompt Engineering Challenge',
    category: 'Prompt Engineering',
    description: 'Master the RCTOF framework for effective Generative AI prompt construction.',
    instructions: 'Select and assemble RCTOF prompt blocks into clear, high-performing prompts.',
    questionIds: q4Docs.map((doc) => doc._id),
    status: 'READY',
    defaultTimeLimit: 30,
    defaultPoints: 1000,
  });

  return {
    quiz1,
    quiz2,
    quiz3,
    quiz4,
    totalQuestionsSeeded: q1Docs.length + q2Docs.length + q3Docs.length + q4Docs.length,
  };
}
