import { connectToDatabase } from '@/lib/db/connect';
import { QuizModel } from '@/models/Quiz';
import { QuestionModel } from '@/models/Question';
import mongoose from 'mongoose';

export async function seedQuizMaterials(trainerIdString: string = '650000000000000000000001') {
  await connectToDatabase();
  const trainerId = new mongoose.Types.ObjectId(trainerIdString);

  // Clear previous seeded materials to ensure exact fresh synchronization
  const seededTitles = [
    'Activity 1: AI or Not? Challenge',
    'Activity 2: AI Technology Detective',
    'Activity 3: AI Solution & Workflow Challenge',
    'Activity 4: Prompt Engineering Challenge',
  ];

  await QuizModel.deleteMany({ title: { $in: seededTitles } });

  // -------------------------------------------------------------
  // QUIZ 1: "Activity 1: AI or Not?" (15 Binary Choice Questions)
  // -------------------------------------------------------------
  const activity1QuestionsData = [
    {
      questionText: "A music app studies a listener's previous songs, skips and playlists, then recommends songs the listener may enjoy.",
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: "The system uses patterns in the listener's behavior to make personalized recommendations. This is an AI use case.",
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: "A refrigerator automatically starts its cooling system when its internal temperature rises above 5°C.",
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 1,
      explanation: 'The refrigerator follows a fixed rule: if the temperature crosses a set threshold, turn cooling on. That is automation, not AI.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: "A banking system examines a customer's transaction patterns and identifies unusual activity that may indicate fraud.",
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The system analyzes data patterns to identify unusual behavior and potential fraud. This is an AI use case.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: 'A phone automatically switches to silent mode every day between 10 PM and 7 AM because the user has configured a schedule.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 1,
      explanation: 'The phone is following a predefined schedule. It does not need to learn or interpret anything, so this is not AI.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: 'An online shopping website looks at what a customer has viewed and purchased and recommends products they might be interested in.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The system uses customer behavior patterns to make personalized recommendations. This is an AI use case.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: 'A car automatically turns on its headlights when a light sensor detects that the surroundings have become dark.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 1,
      explanation: 'A sensor detects a simple condition and triggers a predefined action. This is ordinary automation, not AI.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: 'A handwriting application analyzes a person\'s handwritten notes and converts them into editable digital text.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The system has to recognize complex visual patterns and interpret them as characters and words. That is an AI capability.',
      category: 'Computer Vision',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'A phone unlocks when its front camera recognizes the user\'s face.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The phone analyzes facial features and compares the detected pattern with the enrolled face. This is an AI use case.',
      category: 'Computer Vision',
      difficulty: 'EASY',
    },
    {
      questionText: 'A travel application predicts that a flight is likely to be delayed by analyzing historical flight patterns, weather information and current flight data.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The system uses data and patterns to predict a future event. That is an AI use case.',
      category: 'Machine Learning',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'A traffic light changes from green to yellow to red according to a programmed timing sequence.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 1,
      explanation: 'A sensor detects a simple condition and the machine follows a predefined safety rule. This is not AI.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: 'A vending machine gives you the selected drink or snack after you insert the required payment.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 1,
      explanation: 'The machine is executing programmed control rules. It is automatic, but it does not require AI.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: 'A photo app automatically groups pictures based on what is visible in them, such as pets, beaches or food.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The app analyzes image content and recognizes visual patterns to categorize photos. That is an AI use case.',
      category: 'Computer Vision',
      difficulty: 'EASY',
    },
    {
      questionText: 'Amazon Alexa understands when you say, "Set an alarm for 6 AM tomorrow."',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The system must interpret human speech and understand the user\'s request. Speech and language understanding are AI capabilities.',
      category: 'NLP',
      difficulty: 'EASY',
    },
    {
      questionText: 'An office printer automatically prints a report every Monday at 9 AM because a schedule was configured.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 1,
      explanation: 'The printer is simply following a schedule that was configured in advance. This is not AI.',
      category: 'AI Basics',
      difficulty: 'EASY',
    },
    {
      questionText: 'A weather app predicts whether it will rain tomorrow by analyzing weather data and patterns.',
      questionType: 'TRUE_FALSE',
      options: ['AI', 'Not AI'],
      correctOptionIndex: 0,
      explanation: 'The system analyzes data and patterns to make a prediction about a future event. This is an AI use case.',
      category: 'Machine Learning',
      difficulty: 'EASY',
    },
  ];

  const q1Docs = await QuestionModel.insertMany(
    activity1QuestionsData.map((q) => ({
      ...q,
      trainerId,
      timeLimit: 15,
      points: 1000,
      tags: ['AI-vs-NotAI', 'Workshop-Activity1'],
    }))
  );

  const quiz1 = await QuizModel.create({
    trainerId,
    title: 'Activity 1: AI or Not? Challenge',
    category: 'AI Foundations',
    description: 'Mini Activity — 15 Situations to classify whether a system uses AI or ordinary automation.',
    instructions: 'Examine each situation and select AI or Not AI based on whether it learns from data or uses fixed rules.',
    questionIds: q1Docs.map((doc) => doc._id),
    status: 'READY',
    defaultTimeLimit: 15,
    defaultPoints: 1000,
  });

  // -------------------------------------------------------------
  // QUIZ 2: "Activity 2: AI Technology Detective" (Exactly 2 Drag & Drop Activities)
  // -------------------------------------------------------------
  const activity2QuestionsData = [
    {
      questionText: 'Activity 1 — Sort the Solutions',
      questionType: 'DRAG_AND_DROP',
      options: [
        'Customer churn prediction',
        'House price prediction',
        'Next month\'s sales forecast',
        'Handwritten digit recognition',
        'Speech recognition',
        'Complex medical image learning',
        'Customer email classification',
        'Meeting summary',
        'Language translation',
        'Factory defect detection',
        'Traffic camera vehicle counting',
        'Reading a barcode from a camera',
      ],
      categories: [
        { id: 'ml', title: 'Traditional Machine Learning', description: 'Structured business data used to predict or classify.' },
        { id: 'dl', title: 'Deep Learning', description: 'Neural networks learn complex patterns from many examples.' },
        { id: 'nlp', title: 'Natural Language Processing (NLP)', description: 'The main job is to understand or work with human language.' },
        { id: 'cv', title: 'Computer Vision', description: 'The main job is to understand images or video.' },
      ],
      categoryAssignments: {
        '0': 'ml',
        '1': 'ml',
        '2': 'ml',
        '3': 'dl',
        '4': 'dl',
        '5': 'dl',
        '6': 'nlp',
        '7': 'nlp',
        '8': 'nlp',
        '9': 'cv',
        '10': 'cv',
        '11': 'cv',
      },
      explanation: 'Drag each of the 12 cards into the category that best describes it. You can also click a card, then click a category.',
      category: 'AI Architectures',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Activity 2 — Choose the AI Combination',
      questionType: 'DRAG_AND_DROP',
      options: [
        'Case 1: A customer-service voice assistant must understand what customers say and use a neural network trained on thousands of voice examples. What combination is needed?',
        'Case 2: A factory wants to use camera images to identify damaged products. What combination is most appropriate?',
        'Case 3: A company wants to predict which employees may leave using salary, tenure, age, department and previous performance data. What is the clearest approach?',
        'Case 4: A company wants to automatically classify customer emails as complaint, question, compliment or refund request. What combination best describes the solution?',
        'Case 5: A security system uses camera footage and a neural network to detect whether violence or fighting is happening in the scene. What combination is needed?',
        'Case 6: A bakery wants to predict how many items it will sell next week using previous sales, prices, promotions, day of the week, seasonality and other sales information. What is the clearest approach?',
      ],
      categories: [
        { id: 'nlp_dl', title: 'NLP + Deep Learning' },
        { id: 'cv_dl', title: 'Computer Vision + Deep Learning' },
        { id: 'cv_tml', title: 'Computer Vision + Traditional Machine Learning' },
        { id: 'nlp_cv', title: 'NLP + Computer Vision' },
        { id: 'nlp_tml', title: 'NLP + Traditional Machine Learning' },
        { id: 'tml', title: 'Traditional Machine Learning only' },
        { id: 'nlp_ml', title: 'NLP + Machine Learning' },
      ],
      categoryAssignments: {
        '0': 'nlp_dl',
        '1': 'cv_dl',
        '2': 'tml',
        '3': 'nlp_ml',
        '4': 'cv_dl',
        '5': 'tml',
      },
      explanation: 'Now choose the best combination for each real-life case. Some cases use one concept; others combine a problem area with a learning approach.',
      category: 'AI Architectures',
      difficulty: 'MEDIUM',
    },
  ];

  const q2Docs = await QuestionModel.insertMany(
    activity2QuestionsData.map((q) => ({
      ...q,
      trainerId,
      timeLimit: 30,
      points: 1000,
      tags: ['AI-Detective', 'Workshop-Activity2'],
    }))
  );

  const quiz2 = await QuizModel.create({
    trainerId,
    title: 'Activity 2: AI Technology Detective',
    category: 'AI Classification',
    description: 'Learn the difference between Traditional ML, Deep Learning, NLP, and Computer Vision.',
    instructions: 'Categorize solutions into technology areas and select the best AI technology combinations.',
    questionIds: q2Docs.map((doc) => doc._id),
    status: 'READY',
    defaultTimeLimit: 30,
    defaultPoints: 1000,
  });

  // -------------------------------------------------------------
  // QUIZ 3: "Activity 3: AI Solution Challenge" (5 Interactive Solution Scenarios)
  // -------------------------------------------------------------
  const activity3QuestionsData = [
    {
      questionText: 'E-Commerce Product Launch & Content Automation',
      questionType: 'SOLUTION_CHALLENGE',
      options: ['A fast-growing e-commerce retail brand needs to launch 50 new products next week. They require 200 tailored social media captions (Instagram, LinkedIn, X) and 50 rich product descriptions adhering to strict brand voice guidelines. Human marketers must review and approve all content before publishing.'],
      explanation: 'The primary requirement is generating creative marketing content from product data with mandatory editorial approval. Generative AI with a Human Approval Gate is the optimal solution architecture.',
      category: 'Marketing & Retail',
      topic: 'Marketing Content',
      difficulty: 'EASY',
      solutionChallengeData: {
        icon: '✍️',
        dept: 'Marketing & Retail',
        answer: 'Generative AI',
        objective: 'Automate bulk marketing content creation while ensuring 100% human editorial oversight.',
        constraints: 'No unreviewed content may be published directly to live social channels.',
        whyApproach: 'The core task is generating creative, varied marketing copy from raw product specs. Generative AI creates new content directly from prompt inputs, which human marketers can edit and approve.',
        capabilities: [
          { text: 'Generate creative text content', isCorrect: true, description: 'Produces captions & descriptions' },
          { text: 'Apply brand voice & tone guidelines', isCorrect: true, description: 'Ensures consistent messaging' },
          { text: 'Parse product specs & attributes', isCorrect: true, description: 'Extracts features from data' },
          { text: 'Create multiple copy variations', isCorrect: true, description: 'Tailors posts for different platforms' },
          { text: 'Human marketer review interface', isCorrect: true, description: 'Enables editorial oversight' },
          { text: 'Access live CRM payment records', isCorrect: false, description: 'Not relevant to content drafting' },
          { text: 'Directly publish without human review', isCorrect: false, description: 'Violates the business constraint' },
          { text: 'Modify product catalog pricing', isCorrect: false, description: 'Irrelevant and dangerous capability' },
          { text: 'Auto-reply to customer complaints', isCorrect: false, description: 'Belongs to customer support, not launch copy' },
        ],
        workflow: [
          { text: 'Import raw product specification data', isCorrect: true },
          { text: 'Generate product descriptions & post drafts', isCorrect: true },
          { text: 'Create alternative variations for platforms', isCorrect: true },
          { text: 'Route drafts to human marketer for review & editing', isCorrect: true },
          { text: 'Approve final copy & schedule for publishing', isCorrect: true },
          { text: 'Update CRM customer purchase records', isCorrect: false },
          { text: 'Issue financial invoices to suppliers', isCorrect: false },
          { text: 'Bypass human review and post directly to social media', isCorrect: false },
        ],
        autonomy: [
          { title: 'Human Approval Gate (Human-in-the-Loop)', isCorrect: true, description: 'AI generates content drafts; human marketer reviews, edits, and gives final approval before publication.' },
          { title: 'Exception-Based Human Oversight', isCorrect: false, description: 'AI publishes standard posts automatically and only asks humans for flagged items — violates the 100% review rule.' },
          { title: 'Full AI Autonomy', isCorrect: false, description: 'AI publishes content directly without human review — violates compliance and brand safety guidelines.' },
        ],
        controlTitle: 'Step 4: Determine Human Control & Governance',
        riskQuestion: {
          title: 'Question 5: Risk & Quality Assurance',
          text: 'What is the primary business risk if the marketing team removes the human review gate from this Generative AI workflow?',
          options: [
            { text: 'Hallucinations in product specifications or pricing errors published to customers.', isCorrect: true },
            { text: 'The AI model running out of storage space on social media servers.', isCorrect: false },
            { text: 'Database queries taking longer to execute during peak sales hours.', isCorrect: false },
            { text: 'Social media algorithms blocking all automated posts.', isCorrect: false },
          ],
          explanation: 'Without human review, Generative AI models can hallucinate false product specifications, misstate return policies, or produce off-brand messaging that causes reputational and legal harm.',
        },
        why: 'The primary requirement is generating creative marketing content from product data with mandatory editorial approval. Generative AI with a Human Approval Gate is the optimal solution architecture.',
      },
    },
    {
      questionText: 'Executive Sales Performance Assistant',
      questionType: 'SOLUTION_CHALLENGE',
      options: ['Every Monday morning, a VP of Sales needs an intelligent summary of weekly CRM data across 5 regional sales teams. The VP requires identification of revenue anomalies, sales pipeline bottlenecks, top-performing reps, and 3 strategic investigation questions for the weekly management call.'],
      explanation: 'The AI works alongside the sales manager. It analyzes information and provides suggestions, while the manager remains responsible for the decision.',
      category: 'Sales Operations',
      topic: 'Sales Manager Assistant',
      difficulty: 'EASY',
      solutionChallengeData: {
        icon: '📊',
        dept: 'Sales Operations',
        answer: 'AI Copilot',
        objective: 'Transform raw weekly CRM tables into actionable executive insights and meeting discussion points.',
        constraints: 'The VP remains fully accountable for all operational decisions; the system must assist, not make sales strategy calls.',
        whyApproach: 'The AI acts as an interactive co-pilot alongside the sales executive. It analyzes complex data and suggests questions, while the executive maintains full decision-making responsibility.',
        capabilities: [
          { text: 'Analyze weekly CRM sales datasets', isCorrect: true, description: 'Parses revenue & pipeline metrics' },
          { text: 'Summarize key regional performance trends', isCorrect: true, description: 'Creates executive summaries' },
          { text: 'Identify statistical anomalies & pipeline drops', isCorrect: true, description: 'Flags unusual variances' },
          { text: 'Suggest strategic questions for sales calls', isCorrect: true, description: 'Prepares manager for meetings' },
          { text: 'Interactive Q&A for deep-dive queries', isCorrect: true, description: 'Allows executive to drill down' },
          { text: 'Automatically send warnings to underperforming reps', isCorrect: false, description: 'Oversteps executive authority' },
          { text: 'Change sales commission structures in payroll', isCorrect: false, description: 'Irrelevant and unauthorized HR action' },
          { text: 'Place product reorders with manufacturers', isCorrect: false, description: 'Supply chain task, not sales analysis' },
          { text: 'Reassign sales territories automatically', isCorrect: false, description: 'Requires human strategic planning' },
        ],
        workflow: [
          { text: 'Ingest weekly sales CRM spreadsheet data', isCorrect: true },
          { text: 'Analyze regional performance & calculate variances', isCorrect: true },
          { text: 'Detect revenue anomalies & pipeline bottlenecks', isCorrect: true },
          { text: 'Generate executive summary & 3 inquiry questions', isCorrect: true },
          { text: 'Sales VP reviews insights & conducts team call', isCorrect: true },
          { text: 'Automatically fire underperforming sales reps', isCorrect: false },
          { text: 'Send mass marketing emails to leads', isCorrect: false },
          { text: 'Alter product pricing in the ecommerce database', isCorrect: false },
        ],
        autonomy: [
          { title: 'Decision Support (AI Copilot)', isCorrect: true, description: 'The AI provides analysis and recommendations; the Sales VP retains full decision authority.' },
          { title: 'Automated Rule Execution', isCorrect: false, description: 'The system automatically adjusts quotas and sends alerts without manager review.' },
          { title: 'Autonomous Management', isCorrect: false, description: 'The AI makes strategic decisions for regional teams without human involvement.' },
        ],
        controlTitle: 'Step 4: Determine Decision Authority & Governance',
        riskQuestion: {
          title: 'Question 5: Executive Decision Governance',
          text: 'Why is an AI Copilot preferred over a fully autonomous AI Agent for executive sales reporting?',
          options: [
            { text: 'Executive decisions require strategic context, market nuances, and human accountability that AI cannot assume.', isCorrect: true },
            { text: 'AI Copilots cost significantly less to host on cloud servers than AI Agents.', isCorrect: false },
            { text: 'AI Agents are incapable of reading spreadsheet data or generating text summaries.', isCorrect: false },
            { text: 'CRM systems do not allow API connections from autonomous software agents.', isCorrect: false },
          ],
          explanation: 'Strategic management decisions require contextual judgment, relationship awareness, and organizational accountability. An AI Copilot empowers decision-makers rather than replacing human accountability.',
        },
        why: 'The goal is supporting a sales manager with data analysis and discussion points. An AI Copilot provides intelligent decision support while keeping the human leader in command.',
      },
    },
    {
      questionText: 'Omnichannel Customer Support & Escalation Agent',
      questionType: 'SOLUTION_CHALLENGE',
      options: ['A telecom provider receives over 10,000 support tickets daily. The company needs an automated system that reads customer tickets, queries billing databases, searches knowledge base articles, updates ticket statuses, issues routine credits under $20, and seamlessly escalates complex disputes to human senior agents.'],
      explanation: 'The AI must complete several connected steps and use business tools to act. That makes an AI Agent the best fit.',
      category: 'Customer Service',
      topic: 'Customer Support Task',
      difficulty: 'MEDIUM',
      solutionChallengeData: {
        icon: '🤖',
        dept: 'Customer Service',
        answer: 'AI Agent',
        objective: 'Automate multi-step customer support handling with autonomous tool usage and intelligent human escalation.',
        constraints: 'Complex edge cases and billing disputes exceeding $20 must be escalated to human agents.',
        whyApproach: 'The task requires multi-step reasoning, autonomous tool usage (CRM, billing, knowledge base), and decision-making with escalation rules. This is the definition of an AI Agent.',
        capabilities: [
          { text: 'Understand customer ticket intent via NLP', isCorrect: true, description: 'Classifies customer requests' },
          { text: 'Query customer account & billing history API', isCorrect: true, description: 'Retrieves account status' },
          { text: 'Search internal Knowledge Base (RAG)', isCorrect: true, description: 'Finds official resolution steps' },
          { text: 'Execute routine refund credit up to $20', isCorrect: true, description: 'Takes action via API' },
          { text: 'Escalate complex cases to human support team', isCorrect: true, description: 'Hands off difficult tickets' },
          { text: 'Generate social media marketing campaigns', isCorrect: false, description: 'Irrelevant to customer support' },
          { text: 'Delete customer account data permanently', isCorrect: false, description: 'Dangerous unauthorized action' },
          { text: 'Change overall company pricing plans', isCorrect: false, description: 'Executive level decision, not support' },
          { text: 'Approve unlimited refund amounts without limits', isCorrect: false, description: 'Violates financial control policy' },
        ],
        workflow: [
          { text: 'Receive customer ticket & analyze intent', isCorrect: true },
          { text: 'Retrieve customer account & billing history', isCorrect: true },
          { text: 'Search Knowledge Base for official solution', isCorrect: true },
          { text: 'Resolve routine issue or apply credit (if <$20)', isCorrect: true },
          { text: 'Escalate complex ticket to human agent with context', isCorrect: true },
          { text: 'Close all incoming tickets without reading them', isCorrect: false },
          { text: 'Draft marketing press releases', isCorrect: false },
          { text: 'Change customer subscription rate globally', isCorrect: false },
        ],
        autonomy: [
          { title: 'Hybrid Exception-Based Autonomy', isCorrect: true, description: 'AI Agent handles routine tickets end-to-end autonomously and escalates complex or high-value cases to human agents.' },
          { title: 'Full Autonomous Authority', isCorrect: false, description: 'AI Agent resolves all tickets including high-dollar disputes without any human oversight — high financial risk.' },
          { title: '100% Manual Approval', isCorrect: false, description: 'Human must approve every routine response — negates the benefit of support automation.' },
        ],
        controlTitle: 'Step 4: Establish Agent Guardrails & Escalation Rules',
        riskQuestion: {
          title: 'Question 5: Agent Security & Financial Control',
          text: 'Which safeguard is essential when deploying an AI Agent authorized to issue financial refunds?',
          options: [
            { text: 'Strict monetary cap limits per transaction and anomaly detection for repeated refund requests.', isCorrect: true },
            { text: 'Disabling all logging to speed up response times for customer inquiries.', isCorrect: false },
            { text: 'Allowing the agent to override manager approval limits during weekend hours.', isCorrect: false },
            { text: 'Using random number generators to decide refund approval amounts.', isCorrect: false },
          ],
          explanation: 'Autonomous agents with API action capabilities must be bounded by strict financial caps, rate limits, and audit logs to prevent fraud, runaway actions, or system exploits.',
        },
        why: 'The system executes multi-step workflows using external tools and APIs, making autonomous decisions within set guardrails. This makes AI Agent the ideal architecture.',
      },
    },
    {
      questionText: 'Predictive Customer Churn Analytics',
      questionType: 'SOLUTION_CHALLENGE',
      options: ['A SaaS subscription platform with 50,000 active users wants to predict which subscribers are most likely to cancel their subscriptions within the next 30 days based on usage metrics, login frequency, support ticket volume, and billing history so account managers can intervene early.'],
      explanation: 'Machine Learning learns patterns from historical data and uses them to predict which customers may cancel. The prediction supports a business decision; it does not make the decision itself.',
      category: 'Customer Analytics',
      topic: 'Customer Churn Prediction',
      difficulty: 'EASY',
      solutionChallengeData: {
        icon: '📈',
        dept: 'Customer Retention',
        answer: 'Machine Learning',
        objective: 'Identify patterns in historical subscriber data to accurately forecast future customer churn risk scores.',
        constraints: 'Predictions must provide risk probabilities; account managers determine intervention strategies.',
        whyApproach: 'Predicting future outcomes based on historical structured data patterns is a classic Machine Learning classification problem.',
        capabilities: [
          { text: 'Extract historical subscriber usage features', isCorrect: true, description: 'Prepares structured training data' },
          { text: 'Train classification ML model on past churn data', isCorrect: true, description: 'Learns churn patterns' },
          { text: 'Evaluate model precision and recall metrics', isCorrect: true, description: 'Validates prediction accuracy' },
          { text: 'Score active subscribers for 30-day churn risk', isCorrect: true, description: 'Outputs probability scores' },
          { text: 'Export high-risk customer segment to account team', isCorrect: true, description: 'Triggers proactive outreach' },
          { text: 'Generate creative social media ad copy', isCorrect: false, description: 'Irrelevant to predictive modeling' },
          { text: 'Automatically cancel customer accounts', isCorrect: false, description: 'Opposite of retention goal!' },
          { text: 'Write blog posts about customer satisfaction', isCorrect: false, description: 'Marketing task, not predictive analytics' },
          { text: 'Chat conversationally with customers on phone calls', isCorrect: false, description: 'NLP chatbot task, not churn ML' },
        ],
        workflow: [
          { text: 'Collect 3 years of subscriber usage & billing data', isCorrect: true },
          { text: 'Clean dataset & engineer behavioral feature columns', isCorrect: true },
          { text: 'Train & validate Machine Learning churn model', isCorrect: true },
          { text: 'Generate monthly churn risk probability scores', isCorrect: true },
          { text: 'Account managers review high-risk list & contact users', isCorrect: true },
          { text: 'Send instant cancellation emails to predicted users', isCorrect: false },
          { text: 'Draft marketing press releases', isCorrect: false },
          { text: 'Delete customer payment history from database', isCorrect: false },
        ],
        autonomy: [
          { title: 'Human Decision on Model Predictions', isCorrect: true, description: 'The ML model scores churn probability; human account managers decide the best outreach and retention offer.' },
          { title: 'Automated Mass Account Penalties', isCorrect: false, description: 'The system automatically restricts accounts flagged as high churn risk.' },
          { title: 'Autonomous Account Termination', isCorrect: false, description: 'The system cancels subscriptions automatically based on prediction thresholds.' },
        ],
        controlTitle: 'Step 4: Define How Predictions Inform Action',
        riskQuestion: {
          title: 'Question 5: Model Maintenance & Concept Drift',
          text: 'Why must Machine Learning churn prediction models be periodically retrained with recent customer data?',
          options: [
            { text: 'Customer behavior, economic factors, and product features change over time, leading to model drift.', isCorrect: true },
            { text: 'Machine Learning models automatically delete themselves if not retrained every month.', isCorrect: false },
            { text: 'Retraining is required to change the background color of the sales dashboard.', isCorrect: false },
            { text: 'Historical data loses its mathematical properties after 30 days.', isCorrect: false },
          ],
          explanation: 'Model drift occurs when real-world environment and customer behavior shift over time. Regular retraining ensures the ML model maintains high accuracy and relevant risk indicators.',
        },
        why: 'Machine Learning learns statistical patterns from historical data to predict future events. The predictions guide human decision-making rather than taking direct autonomous actions.',
      },
    },
    {
      questionText: 'Enterprise Employee Leave Approval & HR Routing',
      questionType: 'SOLUTION_CHALLENGE',
      options: ['An enterprise company with 5,000 employees wants to automate the submission, rule validation, manager notification, leave balance deduction, and HRIS syncing for routine paid time off (PTO) requests according to explicit company HR policy rules.'],
      explanation: 'The process follows predefined rules. No learning, prediction or content generation is required, so Automation is the simplest solution.',
      category: 'HR Operations',
      topic: 'Employee Leave Request',
      difficulty: 'EASY',
      solutionChallengeData: {
        icon: '🔄',
        dept: 'HR Operations',
        answer: 'Automation',
        objective: 'Execute a reliable, deterministic process following strict predefined business rules without error.',
        constraints: 'Process must strictly follow company policy rules; incomplete or invalid requests must be rejected immediately.',
        whyApproach: 'The leave request process follows explicit, fixed business rules with no requirement for statistical learning or creative text generation. Rule-Based Automation is the simplest, most reliable solution.',
        capabilities: [
          { text: 'Trigger process on employee form submission', isCorrect: true, description: 'Initiates workflow' },
          { text: 'Validate required fields & leave balance rules', isCorrect: true, description: 'Enforces policy compliance' },
          { text: 'Route request to employee\'s direct manager', isCorrect: true, description: 'Sends approval task' },
          { text: 'Sync approved leave with HRIS & calendar API', isCorrect: true, description: 'Updates corporate systems' },
          { text: 'Send status notification to employee', isCorrect: true, description: 'Keeps employee informed' },
          { text: 'Predict employee turnover likelihood', isCorrect: false, description: 'ML task, not routine PTO routing' },
          { text: 'Generate creative vacation itinerary ideas', isCorrect: false, description: 'Irrelevant Generative AI task' },
          { text: 'Train neural network on employee resumes', isCorrect: false, description: 'Deep Learning task, not workflow automation' },
          { text: 'Allow employees to approve their own requests', isCorrect: false, description: 'Violates HR policy guardrails' },
        ],
        workflow: [
          { text: 'Employee submits digital leave request form', isCorrect: true },
          { text: 'Validate required data & check leave balance eligibility', isCorrect: true },
          { text: 'Route approval notification to manager', isCorrect: true },
          { text: 'Manager approves or rejects request', isCorrect: true },
          { text: 'Update HRIS balance, sync calendar & notify employee', isCorrect: true },
          { text: 'Train ML model to predict employee performance', isCorrect: false },
          { text: 'Generate AI promotional video for company', isCorrect: false },
          { text: 'Bypass manager approval and grant unearned leave', isCorrect: false },
        ],
        autonomy: [
          { title: 'Strict Business Rule Enforcement', isCorrect: true, description: 'If required information is missing or leave balance is insufficient, the system halts and notifies the employee to correct it.' },
          { title: 'AI Prediction Guessing', isCorrect: false, description: 'If data is missing, an AI model guesses the employee\'s intent and fills in random dates.' },
          { title: 'Automatic Unconditional Approval', isCorrect: false, description: 'If data is missing, the system approves the request automatically.' },
        ],
        controlTitle: 'Step 4: Define Policy Exception Handling',
        riskQuestion: {
          title: 'Question 5: Automation vs Machine Learning Choice',
          text: 'Why is Rule-Based Automation superior to Machine Learning for standard employee leave approvals?',
          options: [
            { text: 'Leave approvals follow deterministic corporate policy rules requiring 100% compliance, not probabilistic predictions.', isCorrect: true },
            { text: 'Rule-Based Automation is impossible to audit or inspect compared to neural networks.', isCorrect: false },
            { text: 'Machine Learning requires internet bandwidth that HR departments do not possess.', isCorrect: false },
            { text: 'Automation scripts can only process requests submitted on paper forms.', isCorrect: false },
          ],
          explanation: 'When business rules are deterministic, explicit, and regulated by policy, standard Rule-Based Automation is faster, cheaper, 100% predictable, and fully auditable compared to probabilistic AI.',
        },
        why: 'The workflow relies strictly on defined corporate rules and conditional logic. No learning or generation is needed, so Rule-Based Automation provides the cleanest, most reliable solution.',
      },
    },

    // Part 2: Workflow Automation Challenges (Sequence)
    {
      questionText: 'Build the Automated Leave Request Workflow in the exact logical sequence:',
      questionType: 'CORRECT_SEQUENCE',
      options: [
        'Form Submitted',
        'Check Leave Details',
        'Manager Approval',
        'Send Approval / Rejection Notification',
      ],
      correctOrder: [0, 1, 2, 3],
      explanation: 'Leave workflow sequence: Form Submitted -> Check Details -> Manager Approval -> Send Notification.',
      category: 'Workflow Automation',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Build the Automated Sales Report Workflow in the exact logical sequence:',
      questionType: 'CORRECT_SEQUENCE',
      options: [
        'Monthly Schedule',
        'Get Sales Data',
        'Prepare Sales Report',
        'Send Report to Management',
      ],
      correctOrder: [0, 1, 2, 3],
      explanation: 'Sales report workflow sequence: Schedule -> Fetch Data -> Prepare Report -> Deliver to Management.',
      category: 'Workflow Automation',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Build the Customer Complaint Automation Workflow in the exact logical sequence:',
      questionType: 'CORRECT_SEQUENCE',
      options: [
        'Complaint Received',
        'Capture Complaint Details',
        'Check Complaint Priority',
        'High Priority → Escalate to Manager',
        'Normal Priority → Send Acknowledgement',
        'Update Complaint Status',
      ],
      correctOrder: [0, 1, 2, 3, 4, 5],
      explanation: 'Complaint workflow: Received -> Capture Details -> Priority Check -> Escalation/Acknowledgement Branches -> Update Status.',
      category: 'Workflow Automation',
      difficulty: 'HARD',
    },

    // Part 3: AI Governance Questions
    {
      questionText: 'A team wants to summarize customer support conversations containing names, emails, and phone numbers. What should the team do before using an AI tool?',
      questionType: 'MCQ',
      options: [
        'Use a public AI tool directly because it is faster',
        'Remove or anonymize sensitive personal information before using AI',
        'Upload everything because the AI tool is only used internally',
        'Ask employees to manually copy sensitive details into public AI prompt boxes',
      ],
      correctOptionIndex: 1,
      explanation: 'Sensitive personal identifiable information (PII) must be anonymized before submitting data to AI services.',
      category: 'AI Governance',
      difficulty: 'EASY',
    },
    {
      questionText: 'An employee uses AI to prepare a financial report. The AI generates an incorrect figure, and the employee submits it to management without checking. Who is responsible for ensuring accuracy?',
      questionType: 'MCQ',
      options: [
        'The AI is responsible because it generated the number',
        'The AI vendor company is responsible for the financial report',
        'The employee/team using the AI must review and verify the output',
        'Nobody is responsible because AI can hallucinate',
      ],
      correctOptionIndex: 2,
      explanation: 'Accountability remains with the human professional using the AI tool.',
      category: 'AI Governance',
      difficulty: 'EASY',
    },
    {
      questionText: 'Which AI use case requires the strongest governance and risk controls?',
      questionType: 'MCQ',
      options: [
        'AI creates ideas for a company\'s social media posts',
        'AI summarizes an internal team meeting',
        'AI recommends whether a job applicant should be hired',
        'AI creates a draft internal newsletter',
      ],
      correctOptionIndex: 2,
      explanation: 'Employment, hiring, and financial credit decisions carry high ethical/legal impact and require stringent governance controls.',
      category: 'AI Governance',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Select all responsible actions to take when an AI chatbot gives inconsistent customer answers:',
      questionType: 'MCQ',
      options: [
        'Monitor chatbot outputs & test with representative questions',
        'Allow the chatbot to run completely unmonitored',
        'Define clear escalation triggers to hand over complex cases to human agents',
        'Investigate and correct recurring errors in the knowledge base',
      ],
      correctOptionIndex: 0,
      explanation: 'Responsible AI deployments require output monitoring, safety testing, human handover rules, and root cause fixes.',
      category: 'AI Governance',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Order the governance steps for introducing an AI system for employee performance data:',
      questionType: 'CORRECT_SEQUENCE',
      options: [
        'Define purpose and intended use',
        'Identify data being used',
        'Assess privacy, security, bias and risks',
        'Establish human oversight and approval',
        'Test the AI system',
        'Monitor system after deployment',
      ],
      correctOrder: [0, 1, 2, 3, 4, 5],
      explanation: 'Governance lifecycle: Purpose -> Data -> Risk Assessment -> Governance & Oversight -> Testing -> Ongoing Monitoring.',
      category: 'AI Governance',
      difficulty: 'HARD',
    },
  ];

  const q3Docs = await QuestionModel.insertMany(
    activity3QuestionsData.map((q) => ({
      ...q,
      trainerId,
      timeLimit: 30,
      points: 1000,
      tags: ['AI-Solution-Challenge', 'Workshop-Activity3'],
    }))
  );

  const quiz3 = await QuizModel.create({
    trainerId,
    title: 'Activity 3: AI Solution & Workflow Challenge',
    category: 'AI Solution Architecture',
    description: 'Solve real-world business scenarios, build end-to-end automated workflows, and master AI governance.',
    instructions: 'Select optimal AI approaches, build ordered workflows, and choose responsible AI governance answers.',
    questionIds: q3Docs.map((doc) => doc._id),
    status: 'READY',
    defaultTimeLimit: 30,
    defaultPoints: 1000,
  });

  // -------------------------------------------------------------
  // QUIZ 4: "Activity 4: Prompt Engineering Challenge (RCTOF)" (4 Prompt Builder Exercises)
  // -------------------------------------------------------------
  const activity4QuestionsData = [
    {
      questionText: 'Exercise 1 — Build an Effective Prompt',
      questionType: 'PROMPT_BUILDER',
      options: [
        'Act as a professional meeting summarization assistant.',
        'The audience is busy managers who need a quick overview.',
        'Summarize the meeting and identify key decisions, action items, and responsible people.',
        'Present the answer with clear headings and bullet points.',
        'Use only information from the supplied transcript and do not invent details.',
        'Act as a meeting participant.',
        'Focus mainly on rewriting the transcript into more formal language.',
        'Present the summary as one continuous paragraph without headings or bullet points.',
        'Include only the main topic discussed in the meeting.',
        'Write the summary without mentioning any action items.',
      ],
      promptBuilderData: {
        scenarioTitle: 'Exercise 1 — Build an Effective Prompt',
        scenarioText: 'A management team wants to use AI to turn a long business meeting transcript into a clear summary. The managers are busy and need the important decisions, action items, and responsibilities quickly. Build a prompt for an AI assistant that clearly defines who the AI should act as, who the response is for, what the AI should achieve, how the answer should be presented, and one clear limitation.',
        instruction: 'Select the useful pieces, arrange them, and review the prompt you created.',
        pieces: [
          { text: 'Use only information from the supplied transcript and do not invent details.', isCorrect: true },
          { text: 'Act as a professional meeting summarization assistant.', isCorrect: true },
          { text: 'Write the summary without mentioning any action items.', isCorrect: false },
          { text: 'Summarize the meeting and identify key decisions, action items, and responsible people.', isCorrect: true },
          { text: 'Focus mainly on rewriting the transcript into more formal language.', isCorrect: false },
          { text: 'The audience is busy managers who need a quick overview.', isCorrect: true },
          { text: 'Act as a meeting participant.', isCorrect: false },
          { text: 'Present the answer with clear headings and bullet points.', isCorrect: true },
          { text: 'Present the summary as one continuous paragraph without headings or bullet points.', isCorrect: false },
          { text: 'Include only the main topic discussed in the meeting.', isCorrect: false },
        ],
      },
      explanation: 'RCTOF Framework: Role (Professional meeting summarization assistant) + Context (Busy managers needing quick overview) + Task (Summarize decisions, action items & responsibilities) + Format (Clear headings & bullet points) + Constraint (Use only supplied transcript).',
      category: 'Prompt Engineering',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Exercise 2 — Improve a Weak Prompt',
      questionType: 'PROMPT_BUILDER',
      options: [
        'Act as a sales performance analyst.',
        'The audience is a sales manager preparing for a management meeting.',
        'Analyze the monthly sales data, identify the best and worst regions, and give three actionable recommendations.',
        'Present the result with a short management summary followed by bullet points.',
        'Use only the supplied sales data and do not invent figures.',
        'Act as a software developer.',
        'The audience is a group of database administrators.',
        'Write Python code to analyze the data.',
        'Create a social media campaign.',
        'Use technical language and include every available detail.',
      ],
      promptBuilderData: {
        scenarioTitle: 'Exercise 2 — Improve a Weak Prompt',
        scenarioText: 'Weak prompt: “Analyze this sales data and make a report.”\n\nBusiness requirement: The sales manager wants monthly sales performance, the best and worst regions, and three actionable recommendations for a management meeting. Improve the prompt by defining the role, context, goal, format and constraint.',
        instruction: 'Select the useful pieces, arrange them, and review the prompt you created.',
        pieces: [
          { text: 'Act as a sales performance analyst.', isCorrect: true },
          { text: 'The audience is a sales manager preparing for a management meeting.', isCorrect: true },
          { text: 'Analyze the monthly sales data, identify the best and worst regions, and give three actionable recommendations.', isCorrect: true },
          { text: 'Present the result with a short management summary followed by bullet points.', isCorrect: true },
          { text: 'Use only the supplied sales data and do not invent figures.', isCorrect: true },
          { text: 'Act as a software developer.', isCorrect: false },
          { text: 'The audience is a group of database administrators.', isCorrect: false },
          { text: 'Write Python code to analyze the data.', isCorrect: false },
          { text: 'Create a social media campaign.', isCorrect: false },
          { text: 'Use technical language and include every available detail.', isCorrect: false },
        ],
      },
      explanation: 'RCTOF Framework: Role (Sales performance analyst) + Context (Sales manager preparing for meeting) + Task (Analyze monthly sales, best/worst regions, 3 recommendations) + Format (Short management summary + bullets) + Constraint (Use supplied data only).',
      category: 'Prompt Engineering',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Exercise 3 — Build a Prompt for a New Situation',
      questionType: 'PROMPT_BUILDER',
      options: [
        'Act as a customer service manager.',
        'The audience is a customer service team.',
        'Create a short response explaining how to handle an angry customer professionally.',
        'Use a numbered list with five practical steps.',
        'Keep the response under 150 words and do not blame the customer.',
        'Act as a graphic designer.',
        'The audience is software engineers.',
        'Write JavaScript code for a customer portal.',
        'Use a long essay format.',
        'Include unrelated product specifications.',
      ],
      promptBuilderData: {
        scenarioTitle: 'Exercise 3 — Build a Prompt for a New Situation',
        scenarioText: 'A customer service team needs an AI assistant to help employees handle angry customers professionally. Build an effective prompt using one clear role, context, goal, format and constraint.',
        instruction: 'Select the useful pieces, arrange them, and review the prompt you created.',
        pieces: [
          { text: 'Act as a customer service manager.', isCorrect: true },
          { text: 'The audience is a customer service team.', isCorrect: true },
          { text: 'Create a short response explaining how to handle an angry customer professionally.', isCorrect: true },
          { text: 'Use a numbered list with five practical steps.', isCorrect: true },
          { text: 'Keep the response under 150 words and do not blame the customer.', isCorrect: true },
          { text: 'Act as a graphic designer.', isCorrect: false },
          { text: 'The audience is software engineers.', isCorrect: false },
          { text: 'Write JavaScript code for a customer portal.', isCorrect: false },
          { text: 'Use a long essay format.', isCorrect: false },
          { text: 'Include unrelated product specifications.', isCorrect: false },
        ],
      },
      explanation: 'RCTOF Framework: Role (Customer service manager) + Context (Customer service team) + Task (Handle angry customers professionally) + Format (Numbered list with 5 steps) + Constraint (Under 150 words & no customer blame).',
      category: 'Prompt Engineering',
      difficulty: 'MEDIUM',
    },
    {
      questionText: 'Exercise 4 — Build a Prompt from a Business Requirement',
      questionType: 'PROMPT_BUILDER',
      options: [
        'Act as an HR communication specialist.',
        'The audience is employees who will receive a company policy update.',
        'Create a clear prompt for AI to explain the policy change and what employees need to do.',
        'Present the answer with a short summary followed by employee action points.',
        'Use only the information provided in the policy and do not invent rules.',
        'Act as a financial trader.',
        'Write a detailed Python application.',
        'Generate a social media advertisement.',
        'Assume information that is not in the policy.',
        'Use technical legal language throughout.',
      ],
      promptBuilderData: {
        scenarioTitle: 'Exercise 4 — Build a Prompt from a Business Requirement',
        scenarioText: 'A company is communicating a policy update to employees. Create an effective prompt that instructs AI to explain the change and clearly tell employees what they need to do. Use one role, context, goal, format and constraint.',
        instruction: 'Select the useful pieces, arrange them, and review the prompt you created.',
        pieces: [
          { text: 'Act as an HR communication specialist.', isCorrect: true },
          { text: 'The audience is employees who will receive a company policy update.', isCorrect: true },
          { text: 'Create a clear prompt for AI to explain the policy change and what employees need to do.', isCorrect: true },
          { text: 'Present the answer with a short summary followed by employee action points.', isCorrect: true },
          { text: 'Use only the information provided in the policy and do not invent rules.', isCorrect: true },
          { text: 'Act as a financial trader.', isCorrect: false },
          { text: 'Write a detailed Python application.', isCorrect: false },
          { text: 'Generate a social media advertisement.', isCorrect: false },
          { text: 'Assume information that is not in the policy.', isCorrect: false },
          { text: 'Use technical legal language throughout.', isCorrect: false },
        ],
      },
      explanation: 'RCTOF Framework: Role (HR communication specialist) + Context (Employees receiving policy update) + Task (Explain policy change & action items) + Format (Short summary + employee action points) + Constraint (Use provided policy info only).',
      category: 'Prompt Engineering',
      difficulty: 'MEDIUM',
    },
  ];

  const q4Docs = await QuestionModel.insertMany(
    activity4QuestionsData.map((q) => ({
      ...q,
      trainerId,
      timeLimit: 30,
      points: 1000,
      tags: ['RCTOF-Prompting', 'Workshop-Activity4'],
    }))
  );

  const quiz4 = await QuizModel.create({
    trainerId,
    title: 'Activity 4: Prompt Engineering Challenge',
    category: 'Prompt Engineering',
    description: 'Master the RCTOF framework for effective Generative AI prompt construction.',
    instructions: 'Select and assemble RCTOF prompt blocks into clear, high-performing prompts.',
    questionIds: q4Docs.map((doc) => doc._id),
    status: 'READY',
    defaultTimeLimit: 30,
    defaultPoints: 1000,
  });

  return {
    quiz1,
    quiz2,
    quiz3,
    quiz4,
    totalQuestionsSeeded: q1Docs.length + q2Docs.length + q3Docs.length + q4Docs.length,
  };
}
